export const demoProjects = [
  {
    id: 'proj-101',
    project_code: 'GEOM-101',
    name: 'Northern Ring Road',
    state: 'Delhi',
    district: 'New Delhi',
    authority: 'NCRTC',
    project_type: 'Highway',
    description: 'Urban ring road expansion and interchange modernization.',
    latitude: 28.6139,
    longitude: 77.209,
    land_required: 240,
    land_acquired: 120,
    affected_families: 320,
    current_stage: 'Compensation',
    status: 'Active',
    compensation_status: 'Pending',
    objection_count: 42,
    legal_case_count: 7,
    rr_status: 'In progress',
    env_clearance_status: 'Approved',
    forest_clearance_status: 'Not required',
    crz_status: 'Cleared',
    doc_completeness_pct: 72,
    approval_pending: true,
    overdue_milestones: 2,
    risk_score: 82,
    risk_level: 'Critical',
    delay_probability: 0.78,
    predicted_delay_days: 38,
    confidence: 0.87,
    primary_driver: 'Compensation backlog',
    source_name: 'Demo seed',
    validation_status: 'approved',
    data_classification: 'REAL',
    imported_at: '2026-09-01T09:00:00.000Z',
    updated_at: '2026-09-20T11:30:00.000Z',
  },
  {
    id: 'proj-102',
    project_code: 'GEOM-102',
    name: 'Eastern Freight Corridor',
    state: 'Odisha',
    district: 'Cuttack',
    authority: 'Ministry of Railways',
    project_type: 'Rail',
    description: 'Freight corridor linking industrial clusters to coast.',
    latitude: 20.4625,
    longitude: 85.883,
    land_required: 540,
    land_acquired: 390,
    affected_families: 610,
    current_stage: 'Award',
    status: 'Active',
    compensation_status: 'Partial',
    objection_count: 28,
    legal_case_count: 11,
    rr_status: 'Pending',
    env_clearance_status: 'Approved',
    forest_clearance_status: 'Pending',
    crz_status: 'Not applicable',
    doc_completeness_pct: 68,
    approval_pending: true,
    overdue_milestones: 4,
    risk_score: 74,
    risk_level: 'High',
    delay_probability: 0.67,
    predicted_delay_days: 29,
    confidence: 0.81,
    primary_driver: 'Forest clearance timing',
    source_name: 'Demo seed',
    validation_status: 'approved',
    data_classification: 'REAL',
    imported_at: '2026-08-15T08:00:00.000Z',
    updated_at: '2026-09-19T14:20:00.000Z',
  },
  {
    id: 'proj-103',
    project_code: 'GEOM-103',
    name: 'Bhilai Water Supply Upgrade',
    state: 'Chhattisgarh',
    district: 'Durg',
    authority: 'Urban Development Dept',
    project_type: 'Water',
    description: 'Water treatment and pipeline modernization for urban supply.',
    latitude: 21.1938,
    longitude: 81.3507,
    land_required: 160,
    land_acquired: 145,
    affected_families: 132,
    current_stage: 'Objection / Hearing',
    status: 'Active',
    compensation_status: 'Pending',
    objection_count: 16,
    legal_case_count: 2,
    rr_status: 'Not started',
    env_clearance_status: 'Under review',
    forest_clearance_status: 'Not required',
    crz_status: 'Not applicable',
    doc_completeness_pct: 82,
    approval_pending: false,
    overdue_milestones: 1,
    risk_score: 48,
    risk_level: 'Medium',
    delay_probability: 0.42,
    predicted_delay_days: 18,
    confidence: 0.76,
    primary_driver: 'Hearing backlog',
    source_name: 'Demo seed',
    validation_status: 'approved',
    data_classification: 'REAL',
    imported_at: '2026-09-02T11:20:00.000Z',
    updated_at: '2026-09-18T12:00:00.000Z',
  },
  {
    id: 'proj-104',
    project_code: 'GEOM-104',
    name: 'Gujarat Industrial Park',
    state: 'Gujarat',
    district: 'Vadodara',
    authority: 'State Industrial Development Corp',
    project_type: 'Industrial',
    description: 'Industrial park development with logistics support corridor.',
    latitude: 22.3072,
    longitude: 73.1812,
    land_required: 420,
    land_acquired: 410,
    affected_families: 275,
    current_stage: 'Possession',
    status: 'Active',
    compensation_status: 'Cleared',
    objection_count: 5,
    legal_case_count: 1,
    rr_status: 'Completed',
    env_clearance_status: 'Approved',
    forest_clearance_status: 'Not required',
    crz_status: 'Not applicable',
    doc_completeness_pct: 90,
    approval_pending: false,
    overdue_milestones: 0,
    risk_score: 23,
    risk_level: 'Low',
    delay_probability: 0.16,
    predicted_delay_days: 6,
    confidence: 0.9,
    primary_driver: 'Low litigation exposure',
    source_name: 'Demo seed',
    validation_status: 'approved',
    data_classification: 'REAL',
    imported_at: '2026-09-05T10:15:00.000Z',
    updated_at: '2026-09-20T08:05:00.000Z',
  },
  {
    id: 'proj-105',
    project_code: 'GEOM-105',
    name: 'Telangana Solar Grid',
    state: 'Telangana',
    district: 'Hyderabad',
    authority: 'Energy Department',
    project_type: 'Power',
    description: 'Solar power grid and transmission expansion at district scale.',
    latitude: 17.385,
    longitude: 78.4867,
    land_required: 310,
    land_acquired: 180,
    affected_families: 210,
    current_stage: 'Notification',
    status: 'Active',
    compensation_status: 'Pending',
    objection_count: 18,
    legal_case_count: 3,
    rr_status: 'Not started',
    env_clearance_status: 'Pending',
    forest_clearance_status: 'Not required',
    crz_status: 'Not applicable',
    doc_completeness_pct: 56,
    approval_pending: true,
    overdue_milestones: 3,
    risk_score: 61,
    risk_level: 'High',
    delay_probability: 0.56,
    predicted_delay_days: 24,
    confidence: 0.8,
    primary_driver: 'Notification and approval delay',
    source_name: 'Demo seed',
    validation_status: 'pending',
    data_classification: 'REAL',
    imported_at: '2026-09-12T07:45:00.000Z',
    updated_at: '2026-09-20T10:10:00.000Z',
  },
];

export const demoAlerts = [
  {
    id: 'alert-1',
    project_id: 'proj-101',
    project_name: 'Northern Ring Road',
    severity: 'Critical',
    reason: 'Compensation backlog has exceeded 30 days beyond schedule.',
    detected_at: '2026-09-20T18:00:00.000Z',
    recommended_action: 'Escalate district compensation committee review.',
    status: 'Open',
  },
  {
    id: 'alert-2',
    project_id: 'proj-102',
    project_name: 'Eastern Freight Corridor',
    severity: 'High',
    reason: 'Forest clearance pending for 4 critical stretches.',
    detected_at: '2026-09-20T16:20:00.000Z',
    recommended_action: 'Trigger inter-agency clearance follow-up.',
    status: 'Open',
  },
  {
    id: 'alert-3',
    project_id: 'proj-105',
    project_name: 'Telangana Solar Grid',
    severity: 'Medium',
    reason: 'Objection hearing count is rising and approvals remain pending.',
    detected_at: '2026-09-19T13:15:00.000Z',
    recommended_action: 'Schedule district hearing resolution meeting.',
    status: 'Open',
  },
  {
    id: 'alert-4',
    project_id: 'proj-103',
    project_name: 'Bhilai Water Supply Upgrade',
    severity: 'Low',
    reason: 'Documentation gap still above threshold after last review.',
    detected_at: '2026-09-18T09:30:00.000Z',
    recommended_action: 'Request field verification of land docs.',
    status: 'Monitoring',
  },
];

export function buildDashboardSummary() {
  const total_projects = demoProjects.length;
  const critical_count = demoProjects.filter((p) => p.risk_level === 'Critical').length;
  const high_count = demoProjects.filter((p) => p.risk_level === 'High').length;
  const medium_count = demoProjects.filter((p) => p.risk_level === 'Medium').length;
  const low_count = demoProjects.filter((p) => p.risk_level === 'Low').length;
  const total_land_ha = demoProjects.reduce((sum, p) => sum + (p.land_required || 0), 0);
  const total_families = demoProjects.reduce((sum, p) => sum + (p.affected_families || 0), 0);
  const avg_risk_score = demoProjects.reduce((sum, p) => sum + (p.risk_score || 0), 0) / total_projects;
  const alerts_open = demoAlerts.filter((a) => a.status === 'Open').length;

  return {
    total_projects,
    critical_count,
    high_count,
    medium_count,
    low_count,
    total_land_ha,
    total_families,
    avg_risk_score: Number(avg_risk_score.toFixed(1)),
    alerts_open,
    data_available: true,
    message: 'Local demo data is active while backend services are unavailable.',
  };
}

export function buildGeojson() {
  return {
    type: 'FeatureCollection',
    features: demoProjects.map((project) => ({
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [Number(project.longitude), Number(project.latitude)],
      },
      properties: {
        id: project.id,
        project_code: project.project_code,
        name: project.name,
        state: project.state,
        district: project.district,
        risk_level: project.risk_level,
        risk_score: project.risk_score,
        delay_probability: project.delay_probability,
      },
    })),
  };
}
